package com.inventoryapp.rcapp.ui.nav

const val ROUTE_LOGIN_AGENT = "login_agent"
const val ROUTE_LOGIN_INTERNAL = "login_internal"
const val ROUTE_REGISTER_AGENT = "register_agent"
const val ROUTE_REGISTER_INTERNAL = "register_internal"
const val ROUTE_HOME_INTERNAL_SCREEN = "home_internal_screen"
const val ROUTE_MAIN_INTERNAL_SCREEN = "main_internal_screen"
const val ROUTE_INTERNAL_STOCK_SCREEN = "internal_stock_screen"
const val ROUTE_INTERNAL_SALES_SCREEN = "internal_sales_screen"
const val ROUTE_HOME = "home"
const val ROUTE_HOME_AGENT_SCREEN = "home_agent_screen"
const val ROUTE_AGENT_STOCK_SCREEN = "agent_stock_screen"
const val ROUTE_AGENT_REQUEST_ORDER_SCREEN = "agent_request_order"
const val ROUTE_ORDER_HISTORY_SCREEN = "route_order_history_screen"
const val ROUTE_STOCK_IN_SCREEN = "route_stock_in_screen"
const val ROUTE_STOCK_OUT_SCREEN = "route_stock_out_screen"
const val AGENT_NAV = "agent_nav"
const val INTERNAL_NAV = "internal_nav"
